import "AudioSessionClient.idl";

namespace Wasapi
{
	interface IAudioSessionCaptureCallback
	{
		void OnFramesAvailable();
	};

	[default_interface]
	runtimeclass AudioSessionCaptureClient : Windows.Foundation.IClosable, IAudioSessionClient
	{
		void Initialize();	// Initialize with no callback, default format and default buffer size
		void Initialize(IAudioSessionCaptureCallback callback);	// Initialize with callback, default format and default buffer size
		void InitializeLoopback();	// Initialize loopback with no callback, default format and default buffer size
		void InitializeLoopback(IAudioSessionCaptureCallback callback);	// Initialize with callback, default format and default buffer size
		UInt32 NextPacketSize { get; };
		Windows.Media.AudioFrame GetFrame();
	};
}