import "AudioSessionCaptureClient.idl";
import "AudioSessionRenderClient.idl";

namespace Wasapi
{
	interface IAudioSessionClient
	{
		void Start();
		void Stop();
		void Reset();
		UInt32 BufferSize{ get; };
		UInt32 Padding{ get; };
		Windows.Foundation.TimeSpan DefaultPeriod{ get; };
		Windows.Foundation.TimeSpan MinimumPeriod{ get; };
		Windows.Foundation.TimeSpan Latency{ get; };
		Windows.Media.MediaProperties.AudioEncodingProperties GetFormat();
		Boolean IsFormatSupported(Windows.Media.MediaProperties.AudioEncodingProperties format);
	};

	[default_interface]
	runtimeclass AudioSessionClient
	{
		static Windows.Foundation.IAsyncOperation<AudioSessionRenderClient> CreateRenderClientAsync(Windows.Devices.Enumeration.DeviceInformation device);
		static Windows.Foundation.IAsyncOperation<AudioSessionRenderClient> CreateRenderClientAsync();
		static Windows.Foundation.IAsyncOperation<AudioSessionCaptureClient> CreateCaptureClientAsync(Windows.Devices.Enumeration.DeviceInformation device);
		static Windows.Foundation.IAsyncOperation<AudioSessionCaptureClient> CreateCaptureClientAsync();
	};
}
