import "AudioSessionCaptureClient.idl";

namespace Wasapi
{
	[default_interface]
	runtimeclass AudioSessionClient
	{
		static Windows.Foundation.IAsyncOperation<AudioSessionClient> CreateAsync(String deviceId);
		void Start();
		void Stop();
		void Reset();
		UInt32 BufferSize{ get; };
		UInt32 Padding{ get; };
		Windows.Foundation.TimeSpan DefaultPeriod{ get; };
		Windows.Foundation.TimeSpan MinimumPeriod{ get; };
		Windows.Foundation.TimeSpan Latency{ get; };
		Windows.Media.MediaProperties.AudioEncodingProperties Format{ get; };
		Boolean IsFormatSupported(Windows.Media.MediaProperties.AudioEncodingProperties format);
		void Initialize(Windows.Foundation.TimeSpan bufferDuration, Windows.Media.MediaProperties.AudioEncodingProperties format);
		void InitializeLoopback(Windows.Foundation.TimeSpan bufferDuration, Windows.Media.MediaProperties.AudioEncodingProperties format);
		AudioSessionCaptureClient CreateCaptureClient();
	};

}
